import Foundation

/// قاموس الترجمات — كل شاشة نترجمها بنضيف مفاتيحها هون تحت تعليق باسم الشاشة.
/// أضيفي مفتاح جديد بالعربي والإنجليزي مع بعض دايماً عشان ما تنكسر الترجمة.
enum AppStrings {

    static let ar: [String: String] = [
        // MARK: - Splash
        "splash_tagline": "جمالكِ الذكي يبدأ هنا ✨",
        "splash_loading": "جاري التحميل...",

        // MARK: - Onboarding
        "onboarding_skip": "تخطي",
        "onboarding_next": "التالي",
        "onboarding_start": "ابدأ الآن",
        "onboarding_1_title": "فحص ذكي لبشرتك",
        "onboarding_1_desc": "مسح ضوئي دقيق باستخدام الذكاء الاصطناعي لتحليل بشرتك وفهم احتياجاتها في ثوانٍ.",
        "onboarding_2_title": "نقاط تقييم البشرة",
        "onboarding_2_desc": "احصلي على تقييم تفصيلي لصحة بشرتك مع تحليل دقيق للمسامات، الهالات، ونضارة الوجه.",
        "onboarding_3_title": "روتين مخصص لكِ",
        "onboarding_3_desc": "جدول عناية يومي مصمم خصيصاً ليناسب نوع بشرتك، مع تتبع مستمر للنتائج وتطور صحة البشرة.",
        "onboarding_1_pill1": "🤖 ذكاء اصطناعي", "onboarding_1_pill2": "📸 تحليل فوري", "onboarding_1_pill3": "✨ دقة عالية",
        "onboarding_2_pill1": "📊 تقييم شامل", "onboarding_2_pill2": "🔍 تحليل دقيق", "onboarding_2_pill3": "💡 نصائح ذكية",
        "onboarding_3_pill1": "📅 روتين يومي", "onboarding_3_pill2": "📈 تتبع التقدم", "onboarding_3_pill3": "🌟 نتائج ملحوظة",

        // MARK: - Login
        "login_welcome": "مرحباً بعودتك 💜",
        "login_email_label": "البريد الإلكتروني",
        "login_password_label": "كلمة المرور",
        "login_remember_me": "تذكرني",
        "login_forgot_password": "نسيت كلمة المرور؟",
        "login_or": "أو",
        "login_no_account": "ليس لديك حساب؟",
        "login_create_account": "إنشاء حساب",
        "login_button": "تسجيل الدخول",
        "login_error_email": "يرجى إدخال بريد إلكتروني صحيح",
        "login_error_password": "يرجى إدخال كلمة المرور",

        // MARK: - Signup
        "signup_title": "حساب جديد",
        "signup_subtitle": "ابدأي رحلتك مع GlowFit ✨",
        "signup_full_name": "الاسم الكامل",
        "signup_email": "البريد الإلكتروني",
        "signup_phone": "رقم الجوال",
        "signup_password": "كلمة المرور",
        "signup_gender": "الجنس",
        "signup_female": "أنثى",
        "signup_male": "ذكر",
        "signup_agree_to": "أوافق على",
        "signup_terms_privacy": "الشروط وسياسة الخصوصية",
        "signup_or": "أو",
        "signup_have_account": "لديك حساب بالفعل؟",
        "signup_login": "تسجيل الدخول",
        "signup_button": "إنشاء الحساب",
        "signup_placeholder_name": "أدخلي اسمك الكامل",
        "signup_placeholder_password": "8 أحرف على الأقل",
        "signup_error_terms": "يرجى الموافقة على الشروط وسياسة الخصوصية أولاً",
        "signup_error_url": "رابط الباك آند غير صحيح",
        "signup_error_data": "خطأ في معالجة البيانات",
        "signup_error_network": "خطأ في الاتصال بالشبكة: %@",
        "signup_error_response": "استجابة غير صالحة من خادم الباك آند",
        "signup_error_exists": "هذا البريد الإلكتروني مسجل عندنا بالفعل. سجّلي دخول بدلاً من ذلك.",
        "signup_error_generic": "حدث خطأ أثناء إنشاء الحساب (رمز الخطأ: %d)",
        "signup_error_already_registered": "هذا البريد الإلكتروني مسجل بالفعل",
        "signup_error_password_length": "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
        "signup_error_invalid_email": "يرجى إدخال بريد إلكتروني صحيح",
        "signup_error_rate_limit": "تم تجاوز حد الطلبات المسموح به، يرجى المحاولة لاحقاً",

        // MARK: - Home
        "home_greeting": "مرحباً 👋",
        "home_skin_score_title": "تقييم بشرتك (آخر فحص)",
        "home_no_scan_yet": "لسا ما سويتِ فحص بشرة ✨",
        "home_no_scan_cta": "دوسي هون لتسويي فحصك الأول وتفعيل التقارير والروتين المخصص",
        "home_no_routine_cta": "لسا ما بنيتي روتينك — دوسي هون لتبنيه ✨",
        "home_quick_scan": "فحص البشرة",
        "home_action_report_title": "تقرير مفصّل",
        "home_action_report_subtitle": "نتائج آخر فحص",
        "home_action_routine_title": "الروتين اليومي",
        "home_action_routine_subtitle": "3 خطوات متبقية",
        "home_routine_morning": "روتينك الصباحي ☀️",
        "home_routine_evening": "روتينك المسائي 🌙",
        "home_no_morning_routine": "ما في روتين صباحي مبني بعد",
        "home_no_evening_routine": "ما في روتين مسائي مبني بعد",
        "tab_home": "الرئيسية",
        "tab_reports": "التقارير",
        "tab_routine": "الروتين",
        "tab_profile": "حسابي",

        // MARK: - Skin Scan
        "scan_title": "فحص البشرة",
        "scan_view_last_result": "عرض آخر نتيجة فحص",
        "scan_lighting_tip": "تأكدي من الإضاءة الجيدة وعدم وجود مكياج للحصول على أدق النتائج ✨",
        "scan_analyzing": "جاري تحليل بشرتك...",
        "scan_analyzing_sub": "الذكاء الاصطناعي يقوم بفحص مسامك والتجاعيد",
        "scan_help_tips": "• استخدمي إضاءة طبيعية جيدة (قرب نافذة مثلاً)\n• شيلي المكياج قبل الفحص\n• خلي وجهك واضح بدون نظارات أو غطاء\n• انظري مباشرة للكاميرا وبمسافة معقولة",
        "scan_result_title": "نتيجة فحص بشرتك",
        "scan_out_of_100": "من 100",
        "scan_health_score": "درجة صحة البشرة",
        "scan_first_scan_note": "🎉 هذا فحصك الأول — رح نقارن نتائجك القادمة فيه",
        "scan_approx_age": "العمر التقريبي للبشرة: %d سنة",
        "scan_problems_solutions": "⚠️ المشاكل والحلول",
        "scan_source": "المصدر: ",
        "scan_detected_problems": "⚠️ مشاكل مكتشفة",
        "scan_recommendations": "توصيات العناية",
        "scan_suggested_products": "🛍 منتجات مقترحة لك",
        "scan_currency": "ر.س",
        "scan_done": "تم",
        "scan_help_title": "نصائح لأدق نتيجة 💡",
        "scan_help_ok": "تمام، فهمت 👍",
        "scan_price_format": "%d ر.س",
        "scan_scanning_guide": "جاري الفحص... يرجى الثبات 📸",
        "scan_frame_face": "ضعي وجهك داخل الإطار 👤",
        "scan_improved": "تحسّن +%d عن الفحص السابق",
        "scan_declined": "تراجع %d عن الفحص السابق",
        "scan_no_change": "بدون تغيير عن الفحص السابق",

        // MARK: - Reports
        "report_no_reports_yet": "لسا ما عندك تقارير",
        "report_no_reports_cta": "سوّي فحص بشرة أول عشان يبدأ يتكوّن تقريرك هون",
        "report_title": "تقرير البشرة",
        "report_before_after": "مقارنة قبل / بعد",
        "report_comparison_title": "مقارنة نتائج آخر %d فحوصات",
        "report_based_on_last_scan": "بناءً على آخر فحص",
        "report_detailed_analysis": "تحليل مفصّل",
        "report_time_evolution": "التطور الزمني",
        "report_ai_advice_title": "نصيحة خبير الذكاء الاصطناعي",
        "report_history": "سجل التقارير",
        "report_filter_title": "فلترة التقرير",
        "report_visible_metrics": "المقاييس المعروضة",
        "report_date_range": "نطاق الفترة الزمنية: آخر %d أسبوع",
        "report_apply_filter": "تطبيق الفلتر",
        "report_detail_title": "تفاصيل التقرير",
        "report_points_suffix": "نقطة",
        "report_findings": "⚠️ ملاحظات مكتشفة",
        "report_problems_solutions": "🩺 المشاكل والحلول",
        "report_care_recommendations": "💡 توصيات العناية",
        "metric_moisture": "مستوى الترطيب",
        "metric_acne": "حب الشباب",
        "metric_dark_circles": "الهالات السوداء",
        "metric_fine_lines": "الخطوط الدقيقة",
        "metric_key_moisture": "الترطيب",
        "metric_key_acne": "حب الشباب",
        "metric_key_darkCircles": "الهالات",
        "metric_key_fineLines": "الخطوط",
        "report_share_intro": "حللت بشرتي بالذكاء الاصطناعي مع GlowFit AI ✨",
        "report_share_score": "درجة صحة بشرتي: %d/100",
        "report_share_cta": "جرّبي أنتِ كمان وشوفي تحليل بشرتك:",
        "report_status_improved": "تحسّن",
        "report_status_declined": "تراجع",
        "report_status_unchanged": "بدون تغيير",

        // MARK: - Routine
        "routine_morning_tab": "الصباح ☀️",
        "routine_evening_tab": "المساء 🌙",
        "routine_no_routine_yet": "لسا ما عندك روتين",
        "routine_no_routine_cta": "بنبني لك روتين صباحي ومسائي مخصص بناءً على آخر فحص بشرة سويتيه",
        "routine_build_now": "بناء روتيني الآن ✨",
        "routine_care_title": "روتين العناية",
        "routine_care_subtitle": "خطواتك اليومية للبشرة",
        "routine_steps_completed_today": "خطوات مكتملة اليوم",
        "routine_streak_days": "%d يوم",
        "routine_steps_label": "الخطوات",
        "routine_add_step": "إضافة خطوة",
        "routine_delete": "حذف",
        "routine_delete_confirm_title": "حذف الخطوة؟",
        "routine_delete_confirm_message": "راح تنحذف هاي الخطوة نهائياً من روتينك.",
        "routine_choose_icon": "اختاري أيقونة",
        "routine_enable_reminder": "تفعيل تذكير يومي",
        "routine_add_step_title": "إضافة خطوة جديدة",
        "routine_add_step_button": "إضافة الخطوة",
        "routine_reminder_time_morning": "الوقت (فترة صباحية ☀️ من 4:00 لـ 11:59 ص)",
        "routine_reminder_time_evening": "الوقت (فترة مسائية 🌙 من 4:00 لـ 11:59 م)",
        "routine_reminder_title": "تذكير: %@",
        "routine_step_default_name": "خطوة",
        "routine_enable_step_reminder": "تفعيل تذكير يومي لهاي الخطوة",
        "routine_save": "حفظ",
        "routine_tip_of_day": "نصيحة اليوم",
        "routine_tip_morning": "نصيحة: ضعي واقي الشمس كآخر خطوة قبل الخروج بـ 15 دقيقة لأفضل حماية ☀️",
        "routine_tip_evening": "نصيحة: تجنبي لمس وجهك بعد السيروم واتركيه يمتص بالكامل قبل النوم 🌙",
        "field_step_name": "اسم الخطوة",
        "field_note_optional": "ملاحظة (اختياري)",
        "routine_all_done_today": "خلصتي كل خطوات اليوم! 🎉",
        "routine_keep_going": "تقدم رائع! استمري 💪",

        // MARK: - Store
        "store_no_products": "ما في منتجات متاحة حالياً",
        "store_title": "المتجر 🛍️",
        "store_subtitle": "منتجات مختارة لبشرتك",
        "store_search_placeholder": "ابحثي عن منتج...",
        "store_ai_picked": "اختار AI منتجاتك!",
        "store_ai_picked_desc": "نسبة التطابق محسوبة بناءً على نوع بشرتك ونتائج فحصك الأخير",
        "store_match_percent": "%d%% تطابق",
        "store_match_with_skin": "%d%% تطابق مع بشرتك",
        "store_add_to_cart": "أضف إلى السلة",
        "store_added_confirm": "أُضيفت ✓",
        "store_add_short": "أضف للسلة",
        "store_default_product_name": "منتج",

        // MARK: - Cart & Orders
        "cart_title": "سلة المشتريات 🛒",
        "cart_empty": "السلة فارغة",
        "cart_empty_cta": "تصفحي المتجر واختاري المنتجات المناسبة لبشرتك",
        "cart_back_to_store": "العودة للمتجر",
        "cart_order_summary": "ملخص الطلب",
        "cart_total": "الإجمالي",
        "cart_price_format": "%d ر.س",
        "cart_checkout": "إتمام الطلب",
        "cart_order_success": "تم استلام طلبك بنجاح! 🎉",
        "cart_track_order": "تتبع الطلب",
        "orders_title": "طلباتي 📦",
        "orders_empty": "لسا ما عندك طلبات",
        "orders_number_format": "طلب #%@",
        "cart_subtotal": "المجموع الفرعي",
        "cart_tax": "الضريبة (15%)",
        "cart_delivery": "التوصيل",
        "cart_free": "مجاني",
        "cart_thank_you": "شكراً لتسوقك معنا. سنقوم بتجهيز طلبك وشحنه في أقرب وقت ممكن.",

        // MARK: - Account / Profile
        "account_logout_confirm": "هل أنت متأكد من تسجيل الخروج؟",
        "account_logout_title": "تسجيل الخروج",
        "account_profile_title": "الملف الشخصي",
        "account_no_name": "بدون اسم",
        "account_premium_desc": "تتمتعين بكافة ميزات الذكاء الاصطناعي",
        "account_manage_subscription": "إدارة الاشتراك",
        "concern_acne_prone": "عرضة للحبوب",
        "concern_dark_circles": "هالات سوداء",
        "concern_sensitive": "حساسة",
        "concern_dryness": "جفاف",
        "concern_wrinkles": "خطوط دقيقة",
        "concern_pigmentation": "تصبغات",
        "account_skin_file": "ملف البشرة",
        "account_current_skin_type": "نوع البشرة الحالي",
        "account_update": "تحديث",
        "account_no_scan_prompt": "لسا ما سويتِ فحص بشرة — دوسي 'تحديث' لتبدئي",
        "account_settings_title": "الإعدادات",
        "account_notifications_title": "الإشعارات والتذكير",
        "account_notifications_subtitle": "تذكير بالروتين اليومي",
        "account_language_title": "لغة التطبيق",
        "account_privacy_title": "الخصوصية والأمان",
        "account_privacy_subtitle": "كلمة المرور، البصمة",
        "account_help_title": "المساعدة والدعم",
        "account_help_subtitle": "الأسئلة الشائعة، تواصل معنا",
        "account_logout": "تسجيل الخروج",
        "lang_name_arabic": "العربية",
        "lang_name_english": "English",
        "lang_option_arabic": "العربية",
        "lang_option_english": "الإنجليزية",
        "edit_profile_title": "تعديل الملف الشخصي",
        "edit_profile_uploading": "جاري رفع الصورة...",
        "edit_profile_change_photo": "تغيير الصورة",
        "edit_profile_save": "حفظ التغييرات",
        "edit_profile_camera": "الكاميرا",
        "edit_profile_photo_library": "مكتبة الصور",
        "field_full_name": "الاسم الكامل",
        "field_email_readonly": "البريد الإلكتروني (غير قابل للتعديل)",
        "field_phone": "رقم الجوال",
        "notif_settings_title": "الإشعارات والتذكير",
        "notif_reminder_time": "وقت التذكير",
        "notif_change": "تغيير",
        "lang_settings_title": "لغة التطبيق",
        "lang_apply": "تطبيق اللغة",
        "privacy_title": "الخصوصية والأمان",
        "privacy_biometric_login": "تسجيل دخول بالبصمة",
        "privacy_change_password": "تغيير كلمة المرور",
        "privacy_change_password_hint": "يُنصح بالتغيير كل 3 أشهر",
        "privacy_data_section": "بيانات الخصوصية",
        "privacy_policy_link": "سياسة الخصوصية",
        "privacy_terms_link": "الشروط والأحكام",
        "privacy_delete_account_link": "حذف الحساب",
        "privacy_delete_account_title": "حذف الحساب نهائياً",
        "privacy_delete_account_message": "سيتم حذف جميع بياناتك وتاريخ فحوصاتك بشكل نهائي ولا يمكن التراجع عن هذا الإجراء.",
        "privacy_biometric_enable_title": "تفعيل البصمة",
        "privacy_biometric_enable_message": "لتفعيل الدخول بالبصمة، سجّلي خروج وسجّلي دخول من جديد بالإيميل وكلمة المرور مرة وحدة — بعدها بتشتغل البصمة تلقائياً بكل مرة.",
        "ok_button": "حسناً",
        "change_password_title": "تغيير كلمة المرور",
        "field_current_password": "كلمة المرور الحالية",
        "field_new_password": "كلمة المرور الجديدة",
        "field_confirm_password": "تأكيد كلمة المرور",
        "change_password_button": "تحديث كلمة المرور",
        "change_password_success_title": "تم التحديث ✅",
        "change_password_success_message": "تم تغيير كلمة المرور بنجاح.",
        "change_password_fill_all": "عبّي كل الحقول",
        "change_password_min_length": "كلمة المرور الجديدة لازم تكون 8 أحرف على الأقل",
        "change_password_mismatch": "كلمة المرور الجديدة وتأكيدها مش متطابقين",
        "notif_empty_title": "لا توجد إشعارات",
        "notif_empty_sub": "ستظهر إشعاراتك هنا عند وصولها",
        "notif_clear_all_message": "هل تريدين تحديد كل الإشعارات كمقروءة؟",
        "notif_title": "الإشعارات",
        "notif_unread_count": "%d غير مقروءة",
        "notif_unread_section": "غير مقروءة",
        "notif_previous_section": "السابقة",
        "notif_clear_all_title": "تحديد الكل كمقروء",
        "notif_mark_all": "تحديد الكل",
        "cancel_button": "إلغاء",
        "notif_filter_all": "الكل",
        "notif_filter_routine": "الروتين",
        "notif_filter_reports": "التقارير",
        "notif_filter_store": "المتجر",
        "otp_title": "تأكيد البريد الإلكتروني",
        "otp_subtitle": "تم إرسال رمز التحقق إلى بريدك الإلكتروني",
        "otp_resend_in": "إعادة الإرسال بعد %@",
        "otp_resend_now": "إعادة إرسال الرمز",
        "forgot_password_title": "استعادة كلمة المرور",
        "forgot_password_subtitle": "أدخلي بريدك الإلكتروني\nوسنرسل لك رابط إعادة تعيين كلمة المرور",
        "forgot_password_email_label": "البريد الإلكتروني",
        "reset_password_title": "تعيين كلمة مرور جديدة",
        "reset_password_subtitle": "أدخلي الرمز اللي وصلك على %@\nوحددي كلمة مرورك الجديدة",
        "reset_password_new": "كلمة المرور الجديدة",
        "reset_password_confirm": "تأكيد كلمة المرور",
        "reset_password_success_message": "تم تعيين كلمة مرورك الجديدة، وسجّلنا دخولك تلقائياً.",
        "before_after_title": "مقارنة قبل / بعد",
        "before_after_need_scans": "تحتاجي فحصين على الأقل للمقارنة",
        "before_after_need_scans_cta": "سوّي فحص بشرة تاني عشان تقدري تشوفي تطوّر بشرتك بمرور الوقت",
        "before_after_before": "قبل",
        "before_after_after": "بعد",
        "before_after_drag_hint": "اسحبي المقبض يميناً أو يساراً للمقارنة",
        "before_after_metrics_compare": "مقارنة المقاييس",
        "before_after_improved": "تحسّن %d%%",
        "before_after_increased": "زاد %d%%",
        "before_after_no_change": "بدون تغيير",
        "before_after_before_percent": "قبل: %d%%",
        "before_after_after_percent": "بعد: %d%%",
        "contact_us_title": "تواصل معنا",
        "contact_email_label": "البريد الإلكتروني",
        "contact_direct_label": "تواصل مباشر",
        "contact_direct_sub": "متاح 9ص–9م",
        "contact_phone_label": "الدعم الهاتفي",
        "contact_or_send_message": "أو أرسلي رسالة",
        "contact_subject_field": "عنوان الرسالة",
        "contact_subject_label": "موضوع الرسالة",
        "contact_details_label": "تفاصيل الرسالة",
        "contact_message_placeholder": "اكتبي رسالتك هنا...",
        "contact_send_message": "إرسال الرسالة",
        "contact_reply_time": "سيتم الرد خلال 24 ساعة عمل",
        "contact_success_message": "تم إرسال رسالتك بنجاح. سيتواصل معك فريق الدعم خلال 24 ساعة.",
        "first_scan_title": "خلينا نتعرف على بشرتك",
        "first_scan_subtitle": "فحص سريع بالذكاء الاصطناعي، وبنبني لك بناءً عليه روتين وتقارير مخصصة بالكامل",
        "first_scan_benefit1": "تقرير كامل عن حالة بشرتك",
        "first_scan_benefit2": "روتين عناية يومي مخصص لك",
        "first_scan_benefit3": "منتجات مقترحة تناسب بشرتك بالضبط",
        "first_scan_start": "ابدئي فحصك الأول ✨",
        "first_scan_skip": "تخطي حالياً",
        "sub_title": "إدارة الاشتراك",
        "sub_active_renews": "الاشتراك نشط • يتجدد 15 يونيو 2025",
        "sub_plans_title": "خطط الاشتراك",
        "sub_includes_title": "ما يتضمنه Premium",
        "sub_feature1": "فحص البشرة غير المحدود بالذكاء الاصطناعي",
        "sub_feature2": "تقارير تفصيلية أسبوعية وشهرية",
        "sub_feature3": "توصيات منتجات مخصصة لبشرتك",
        "sub_feature4": "استشارات خبراء الجلدية",
        "sub_feature5": "روتين ذكي يتكيف مع بشرتك",
        "sub_confirm_plan": "تأكيد الاشتراك في خطة %@",
        "sub_plan_monthly": "الشهرية",
        "sub_plan_yearly": "السنوية",
        "sub_plan_lifetime": "مدى الحياة",
        "sub_cancel": "إلغاء الاشتراك",
        "sub_cancel_note": "يمكن الإلغاء في أي وقت قبل 24 ساعة من التجديد",
        "sub_cancel_confirm_message": "سيتم إلغاء اشتراكك في نهاية الفترة الحالية ولن يتم تجديده.",
        "sub_plan_monthly_title": "شهري",
        "sub_plan_yearly_title": "سنوي",
        "sub_plan_lifetime_title": "مدى الحياة",
        "sub_period_month": "/ شهر",
        "sub_period_year": "/ سنة",
        "sub_period_once": "مرة واحدة",
        "sub_badge_save": "وفري 32%",
        "sub_badge_best_value": "الأفضل قيمة",
        "sub_cancel_confirm_button": "تأكيد الإلغاء",
        "sub_keep_subscription": "الإبقاء على الاشتراك",
        "skin_type_combination": "مختلطة",
        "skin_type_combination_desc": "دهنية في المنطقة T وجافة في الخدين",
        "skin_type_dry": "جافة",
        "skin_type_dry_desc": "تحتاج لترطيب مستمر ومكثف",
        "skin_type_oily": "دهنية",
        "skin_type_oily_desc": "إفراز زائد للزيوت طوال اليوم",
        "skin_type_normal": "عادية",
        "skin_type_normal_desc": "بشرة متوازنة ومتجانسة",
        "skin_type_sensitive": "حساسة",
        "skin_type_sensitive_desc": "تتفاعل بسرعة مع المنتجات",
        "skin_profile_title": "ملف بشرتك",
        "skin_profile_concerns": "المخاوف المكتشفة",
        "skin_profile_update_note": "عشان تتحدّث، لازم تسوّي فحص جديد — مش تعديل يدوي، عشان النتيجة تضل دقيقة وموثوقة 💡",
        "skin_profile_no_scan": "لسا ما سويتِ فحص بشرة",
        "skin_profile_no_scan_cta": "روحي لتبويب 'فحص البشرة' وسوّي فحصك الأول عشان يظهر هون نوع بشرتك الحقيقي",
        "done_button": "تم",
        "biometric_no_saved_creds": "ما في بيانات دخول محفوظة، سجّلي دخول عادي أول مرة",
        "biometric_reason": "استخدمي بصمتك لتسجيل الدخول بسرعة",
        "apple_auth_no_data": "تعذّر الحصول على بيانات الدخول من آبل",
        "apple_auth_failed": "تعذّر تسجيل الدخول بآبل: %@",
        "google_auth_start_failed": "تعذّر بدء تسجيل الدخول",
        "google_auth_failed": "تعذّر تسجيل الدخول بجوجل: %@",
        "google_auth_no_data": "تعذّر الحصول على بيانات الدخول من جوجل",
        "keyboard_done": "تم",
        "home_routine_default_summary": "استمري بروتينك اليومي 🌟",
        "home_view_all": "عرض الكل",
        "login_face_id": "الدخول ببصمة الوجه",
        "login_touch_id": "الدخول ببصمة الإصبع",
        "api_invalid_url": "رابط غير صحيح",
        "api_network_error": "خطأ بالاتصال: %@",
        "api_network_error2": "خطأ في الاتصال بالشبكة: %@",
        "api_invalid_response": "استجابة غير صالحة من الخادم",
        "api_read_response_failed": "تعذّر قراءة استجابة الخادم",
        "api_read_response_failed2": "تعذّر قراءة الاستجابة",
        "api_no_logged_user": "لا يوجد مستخدم مسجل دخول",
        "api_must_login_first": "لازم تسجّلي دخول أول",
        "api_need_scan_first": "لازم تسوّي فحص بشرة أول عشان نبني روتين مناسب لك",
        "api_wrong_current_password": "كلمة المرور الحالية غير صحيحة",
        "api_order_partial_save": "تم إنشاء الطلب بس تعذّر حفظ تفاصيله بالكامل",
        "api_read_result_failed": "تعذّر قراءة نتيجة التحليل",
        "api_upload_image_failed": "تعذّر رفع الصورة: %@",
        "api_upload_image_failed2": "تعذّر رفع الصورة",
        "api_save_changes_failed": "تعذّر حفظ التعديلات",
        "api_load_account_failed": "تعذّر تحميل بيانات الحساب",
        "api_update_password_retry": "تعذّر تحديث كلمة المرور، حاولي مرة ثانية",
        "api_update_password_failed": "تعذّر تحديث كلمة المرور",
        "api_build_routine_retry": "تعذّر بناء الروتين بالكامل، حاولي مرة ثانية",
        "api_verify_account_failed": "تعذّر التأكد من حسابك، سجّلي دخول من جديد",
        "api_server_connect_failed": "تعذّر الاتصال بالخادم",
        "api_create_order_failed": "تعذّر إنشاء الطلب",
        "api_send_reset_link_retry": "تعذّر إرسال رابط الاستعادة، حاول مرة ثانية",
        "api_send_message_failed": "تعذّر إرسال الرسالة",
        "api_empty_response": "استجابة فاضية من الخادم",
        "api_wrong_login_data": "بيانات الدخول غير صحيحة",
        "api_wrong_otp": "رمز التحقق غير صحيح",
        "api_wrong_or_expired_code": "الرمز غير صحيح أو منتهي الصلاحية",
        "api_apple_login_failed_generic": "تعذّر تسجيل الدخول بآبل",
        "api_google_login_failed_generic": "تعذّر تسجيل الدخول بجوجل",
        "notif_scan_ready_title": "فحصك جاهز ✨",
        "notif_scan_ready_body": "درجة صحة بشرتك: %d/100 — دوسي لتشوفي التفاصيل الكاملة",
        "notif_order_update_title": "تحديث طلبك 🛍️",
        "order_status_pending": "قيد المعالجة ⏳",
        "order_status_shipped": "تم شحن طلبك 📦",
        "order_status_delivered": "تم توصيل طلبك ✅",
        "order_status_cancelled": "تم إلغاء طلبك ❌",
        "order_status_default": "تحديث على طلبك",
        "routine_tpl_cleanse_title": "تنظيف البشرة",
        "routine_tpl_cleanse_note_morning": "استخدمي غسول لطيف مناسب لنوع بشرتك",
        "routine_tpl_cleanse_note_evening": "أزيلي أي مكياج أو شوائب أول الروتين المسائي",
        "routine_tpl_treatment_title": "علاج مركّز",
        "routine_tpl_treatment_note": "سيروم يستهدف مشاكل بشرتك المكتشفة",
        "routine_tpl_moisturize_title": "ترطيب",
        "routine_tpl_moisturize_note": "مرطب مناسب لنوع بشرتك",
        "routine_tpl_moisturize_night_title": "ترطيب ليلي",
        "routine_tpl_moisturize_night_note": "مرطب ليلي يساعد ببشرتك أثناء النوم",
        "routine_tpl_sunscreen_title": "حماية من الشمس",
        "routine_tpl_sunscreen_note": "واقي شمس SPF 30 فأكثر — خطوة لا يمكن تجاهلها صباحاً",
        "faq_q1": "كيف أبدأ فحص البشرة؟",
        "faq_a1": "اضغطي على زر 'فحص البشرة' في الشريط السفلي، ثم وجّهي الكاميرا نحو وجهك في ضوء جيد واتبعي التعليمات.",
        "faq_q2": "كم مرة يجب أن أفحص بشرتي؟",
        "faq_a2": "ننصح بالفحص الأسبوعي للحصول على تتبع دقيق للتحسينات والتغيرات في بشرتك.",
        "faq_q3": "هل يمكنني تغيير روتيني اليومي؟",
        "faq_a3": "نعم، يمكنك تعديل الروتين من شاشة الروتين والضغط على زر التعديل لكل خطوة.",
        "faq_q4": "كيف أُلغي اشتراكي في Premium؟",
        "faq_a4": "اذهبي إلى الملف الشخصي > إدارة الاشتراك، ثم اتبعي خيار إلغاء الاشتراك.",
        "help_title": "المساعدة والدعم",
        "help_faq_section": "الأسئلة الشائعة",
        "help_contact_support": "إرسال رسالة للدعم",
        "routine_morning_name": "روتين الصباح",
        "routine_evening_name": "روتين المساء",
    ]

    static let en: [String: String] = [
        // MARK: - Splash
        "splash_tagline": "Your smart glow starts here ✨",
        "splash_loading": "Loading...",

        // MARK: - Onboarding
        "onboarding_skip": "Skip",
        "onboarding_next": "Next",
        "onboarding_start": "Get Started",
        "onboarding_1_title": "Smart Skin Scan",
        "onboarding_1_desc": "A precise AI-powered scan that analyzes your skin and understands its needs in seconds.",
        "onboarding_2_title": "Skin Health Score",
        "onboarding_2_desc": "Get a detailed assessment of your skin health with accurate analysis of pores, dark circles, and radiance.",
        "onboarding_3_title": "A Routine Made For You",
        "onboarding_3_desc": "A daily care schedule designed specifically for your skin type, with continuous tracking of results and skin health progress.",
        "onboarding_1_pill1": "🤖 AI Powered", "onboarding_1_pill2": "📸 Instant Analysis", "onboarding_1_pill3": "✨ High Accuracy",
        "onboarding_2_pill1": "📊 Full Assessment", "onboarding_2_pill2": "🔍 Precise Analysis", "onboarding_2_pill3": "💡 Smart Tips",
        "onboarding_3_pill1": "📅 Daily Routine", "onboarding_3_pill2": "📈 Progress Tracking", "onboarding_3_pill3": "🌟 Visible Results",

        // MARK: - Login
        "login_welcome": "Welcome back 💜",
        "login_email_label": "Email",
        "login_password_label": "Password",
        "login_remember_me": "Remember me",
        "login_forgot_password": "Forgot password?",
        "login_or": "or",
        "login_no_account": "Don't have an account?",
        "login_create_account": "Create account",
        "login_button": "Log In",
        "login_error_email": "Please enter a valid email",
        "login_error_password": "Please enter your password",

        // MARK: - Signup
        "signup_title": "New Account",
        "signup_subtitle": "Start your journey with GlowFit ✨",
        "signup_full_name": "Full Name",
        "signup_email": "Email",
        "signup_phone": "Phone Number",
        "signup_password": "Password",
        "signup_gender": "Gender",
        "signup_female": "Female",
        "signup_male": "Male",
        "signup_agree_to": "I agree to the",
        "signup_terms_privacy": "Terms & Privacy Policy",
        "signup_or": "or",
        "signup_have_account": "Already have an account?",
        "signup_login": "Log In",
        "signup_button": "Create Account",
        "signup_placeholder_name": "Enter your full name",
        "signup_placeholder_password": "At least 8 characters",
        "signup_error_terms": "Please agree to the Terms & Privacy Policy first",
        "signup_error_url": "Invalid backend URL",
        "signup_error_data": "Error processing data",
        "signup_error_network": "Network connection error: %@",
        "signup_error_response": "Invalid response from backend server",
        "signup_error_exists": "This email is already registered. Please log in instead.",
        "signup_error_generic": "An error occurred while creating the account (error code: %d)",
        "signup_error_already_registered": "This email is already registered",
        "signup_error_password_length": "Password must be at least 8 characters",
        "signup_error_invalid_email": "Please enter a valid email",
        "signup_error_rate_limit": "Request limit exceeded, please try again later",

        // MARK: - Home
        "home_greeting": "Hello 👋",
        "home_skin_score_title": "Your Skin Score (Last Scan)",
        "home_no_scan_yet": "You haven't scanned your skin yet ✨",
        "home_no_scan_cta": "Tap here to do your first scan and unlock reports and a custom routine",
        "home_no_routine_cta": "You haven't built your routine yet — tap here to build it ✨",
        "home_quick_scan": "Skin Scan",
        "home_action_report_title": "Detailed Report",
        "home_action_report_subtitle": "Latest scan results",
        "home_action_routine_title": "Daily Routine",
        "home_action_routine_subtitle": "3 steps remaining",
        "home_routine_morning": "Your Morning Routine ☀️",
        "home_routine_evening": "Your Evening Routine 🌙",
        "home_no_morning_routine": "No morning routine built yet",
        "home_no_evening_routine": "No evening routine built yet",
        "tab_home": "Home",
        "tab_reports": "Reports",
        "tab_routine": "Routine",
        "tab_profile": "Profile",

        // MARK: - Skin Scan
        "scan_title": "Skin Scan",
        "scan_view_last_result": "View last scan result",
        "scan_lighting_tip": "Make sure you have good lighting and no makeup for the most accurate results ✨",
        "scan_analyzing": "Analyzing your skin...",
        "scan_analyzing_sub": "AI is examining your pores and wrinkles",
        "scan_help_tips": "• Use good natural lighting (near a window, for example)\n• Remove makeup before scanning\n• Keep your face clear without glasses or coverings\n• Look directly at the camera at a reasonable distance",
        "scan_result_title": "Your Skin Scan Result",
        "scan_out_of_100": "out of 100",
        "scan_health_score": "Skin Health Score",
        "scan_first_scan_note": "🎉 This is your first scan — we'll compare your future results to it",
        "scan_approx_age": "Approximate skin age: %d years",
        "scan_problems_solutions": "⚠️ Problems & Solutions",
        "scan_source": "Source: ",
        "scan_detected_problems": "⚠️ Detected Issues",
        "scan_recommendations": "Care Recommendations",
        "scan_suggested_products": "🛍 Suggested Products For You",
        "scan_currency": "SAR",
        "scan_done": "Done",
        "scan_help_title": "Tips For Best Results 💡",
        "scan_help_ok": "Got it 👍",
        "scan_price_format": "%d SAR",
        "scan_scanning_guide": "Scanning... please hold still 📸",
        "scan_frame_face": "Place your face inside the frame 👤",
        "scan_improved": "Improved +%d since last scan",
        "scan_declined": "Down %d since last scan",
        "scan_no_change": "No change since last scan",

        // MARK: - Reports
        "report_no_reports_yet": "You don't have any reports yet",
        "report_no_reports_cta": "Do a skin scan first so your report can start forming here",
        "report_title": "Skin Report",
        "report_before_after": "Before / After Comparison",
        "report_comparison_title": "Comparing results of last %d scans",
        "report_based_on_last_scan": "Based on your last scan",
        "report_detailed_analysis": "Detailed Analysis",
        "report_time_evolution": "Progress Over Time",
        "report_ai_advice_title": "AI Expert Advice",
        "report_history": "Report History",
        "report_filter_title": "Filter Report",
        "report_visible_metrics": "Visible Metrics",
        "report_date_range": "Time range: last %d weeks",
        "report_apply_filter": "Apply Filter",
        "report_detail_title": "Report Details",
        "report_points_suffix": "points",
        "report_findings": "⚠️ Detected Notes",
        "report_problems_solutions": "🩺 Problems & Solutions",
        "report_care_recommendations": "💡 Care Recommendations",
        "metric_moisture": "Moisture Level",
        "metric_acne": "Acne",
        "metric_dark_circles": "Dark Circles",
        "metric_fine_lines": "Fine Lines",
        "metric_key_moisture": "Moisture",
        "metric_key_acne": "Acne",
        "metric_key_darkCircles": "Dark Circles",
        "metric_key_fineLines": "Fine Lines",
        "report_share_intro": "I analyzed my skin with AI using GlowFit AI ✨",
        "report_share_score": "My skin health score: %d/100",
        "report_share_cta": "Try it yourself and see your skin analysis:",
        "report_status_improved": "Improved",
        "report_status_declined": "Declined",
        "report_status_unchanged": "Unchanged",

        // MARK: - Routine
        "routine_morning_tab": "Morning ☀️",
        "routine_evening_tab": "Evening 🌙",
        "routine_no_routine_yet": "You don't have a routine yet",
        "routine_no_routine_cta": "We'll build you a custom morning and evening routine based on your last skin scan",
        "routine_build_now": "Build My Routine Now ✨",
        "routine_care_title": "Care Routine",
        "routine_care_subtitle": "Your daily skin steps",
        "routine_steps_completed_today": "Steps completed today",
        "routine_streak_days": "%d days",
        "routine_steps_label": "Steps",
        "routine_add_step": "Add Step",
        "routine_delete": "Delete",
        "routine_delete_confirm_title": "Delete this step?",
        "routine_delete_confirm_message": "This step will be permanently removed from your routine.",
        "routine_choose_icon": "Choose an icon",
        "routine_enable_reminder": "Enable daily reminder",
        "routine_add_step_title": "Add New Step",
        "routine_add_step_button": "Add Step",
        "routine_reminder_time_morning": "Time (morning window ☀️ 4:00 AM to 11:59 AM)",
        "routine_reminder_time_evening": "Time (evening window 🌙 4:00 PM to 11:59 PM)",
        "routine_reminder_title": "Reminder: %@",
        "routine_step_default_name": "Step",
        "routine_enable_step_reminder": "Enable daily reminder for this step",
        "routine_save": "Save",
        "routine_tip_of_day": "Tip of the Day",
        "routine_tip_morning": "Tip: Apply sunscreen as your last step 15 minutes before going out for best protection ☀️",
        "routine_tip_evening": "Tip: Avoid touching your face after applying serum and let it fully absorb before sleeping 🌙",
        "field_step_name": "Step Name",
        "field_note_optional": "Note (optional)",
        "routine_all_done_today": "You've completed all of today's steps! 🎉",
        "routine_keep_going": "Great progress! Keep going 💪",

        // MARK: - Store
        "store_no_products": "No products available right now",
        "store_title": "Store 🛍️",
        "store_subtitle": "Products picked for your skin",
        "store_search_placeholder": "Search for a product...",
        "store_ai_picked": "AI Picked Your Products!",
        "store_ai_picked_desc": "Match percentage calculated based on your skin type and latest scan results",
        "store_match_percent": "%d%% match",
        "store_match_with_skin": "%d%% match with your skin",
        "store_add_to_cart": "Add to Cart",
        "store_added_confirm": "Added ✓",
        "store_add_short": "Add to Cart",
        "store_default_product_name": "Product",

        // MARK: - Cart & Orders
        "cart_title": "Shopping Cart 🛒",
        "cart_empty": "Your cart is empty",
        "cart_empty_cta": "Browse the store and pick products suited for your skin",
        "cart_back_to_store": "Back to Store",
        "cart_order_summary": "Order Summary",
        "cart_total": "Total",
        "cart_price_format": "%d SAR",
        "cart_checkout": "Checkout",
        "cart_order_success": "Your order was placed successfully! 🎉",
        "cart_track_order": "Track Order",
        "orders_title": "My Orders 📦",
        "orders_empty": "You don't have any orders yet",
        "orders_number_format": "Order #%@",
        "cart_subtotal": "Subtotal",
        "cart_tax": "Tax (15%)",
        "cart_delivery": "Delivery",
        "cart_free": "Free",
        "cart_thank_you": "Thank you for shopping with us. We'll prepare and ship your order as soon as possible.",

        // MARK: - Account / Profile
        "account_logout_confirm": "Are you sure you want to log out?",
        "account_logout_title": "Log Out",
        "account_profile_title": "Profile",
        "account_no_name": "No name",
        "account_premium_desc": "You're enjoying all AI features",
        "account_manage_subscription": "Manage Subscription",
        "concern_acne_prone": "Acne Prone",
        "concern_dark_circles": "Dark Circles",
        "concern_sensitive": "Sensitive",
        "concern_dryness": "Dryness",
        "concern_wrinkles": "Fine Lines",
        "concern_pigmentation": "Pigmentation",
        "account_skin_file": "Skin Profile",
        "account_current_skin_type": "Current Skin Type",
        "account_update": "Update",
        "account_no_scan_prompt": "You haven't done a skin scan yet — tap 'Update' to get started",
        "account_settings_title": "Settings",
        "account_notifications_title": "Notifications & Reminders",
        "account_notifications_subtitle": "Daily routine reminder",
        "account_language_title": "App Language",
        "account_privacy_title": "Privacy & Security",
        "account_privacy_subtitle": "Password, biometrics",
        "account_help_title": "Help & Support",
        "account_help_subtitle": "FAQ, contact us",
        "account_logout": "Log Out",
        "lang_name_arabic": "العربية",
        "lang_name_english": "English",
        "lang_option_arabic": "Arabic",
        "lang_option_english": "English",
        "edit_profile_title": "Edit Profile",
        "edit_profile_uploading": "Uploading photo...",
        "edit_profile_change_photo": "Change Photo",
        "edit_profile_save": "Save Changes",
        "edit_profile_camera": "Camera",
        "edit_profile_photo_library": "Photo Library",
        "field_full_name": "Full Name",
        "field_email_readonly": "Email (cannot be changed)",
        "field_phone": "Phone Number",
        "notif_settings_title": "Notifications & Reminders",
        "notif_reminder_time": "Reminder Time",
        "notif_change": "Change",
        "lang_settings_title": "App Language",
        "lang_apply": "Apply Language",
        "privacy_title": "Privacy & Security",
        "privacy_biometric_login": "Biometric Login",
        "privacy_change_password": "Change Password",
        "privacy_change_password_hint": "We recommend changing it every 3 months",
        "privacy_data_section": "Privacy Data",
        "privacy_policy_link": "Privacy Policy",
        "privacy_terms_link": "Terms & Conditions",
        "privacy_delete_account_link": "Delete Account",
        "privacy_delete_account_title": "Permanently Delete Account",
        "privacy_delete_account_message": "All your data and scan history will be permanently deleted and this action cannot be undone.",
        "privacy_biometric_enable_title": "Enable Biometric Login",
        "privacy_biometric_enable_message": "To enable biometric login, log out and log back in with your email and password once — after that, biometric login will work automatically every time.",
        "ok_button": "OK",
        "change_password_title": "Change Password",
        "field_current_password": "Current Password",
        "field_new_password": "New Password",
        "field_confirm_password": "Confirm Password",
        "change_password_button": "Update Password",
        "change_password_success_title": "Updated ✅",
        "change_password_success_message": "Your password has been changed successfully.",
        "change_password_fill_all": "Please fill in all fields",
        "change_password_min_length": "New password must be at least 8 characters",
        "change_password_mismatch": "New password and confirmation don't match",
        "notif_empty_title": "No notifications",
        "notif_empty_sub": "Your notifications will appear here when they arrive",
        "notif_clear_all_message": "Do you want to mark all notifications as read?",
        "notif_title": "Notifications",
        "notif_unread_count": "%d unread",
        "notif_unread_section": "Unread",
        "notif_previous_section": "Previous",
        "notif_clear_all_title": "Mark all as read",
        "notif_mark_all": "Mark all",
        "cancel_button": "Cancel",
        "notif_filter_all": "All",
        "notif_filter_routine": "Routine",
        "notif_filter_reports": "Reports",
        "notif_filter_store": "Store",
        "otp_title": "Confirm Your Email",
        "otp_subtitle": "A verification code was sent to your email",
        "otp_resend_in": "Resend in %@",
        "otp_resend_now": "Resend Code",
        "forgot_password_title": "Recover Password",
        "forgot_password_subtitle": "Enter your email\nand we'll send you a password reset link",
        "forgot_password_email_label": "Email",
        "reset_password_title": "Set New Password",
        "reset_password_subtitle": "Enter the code sent to %@\nand set your new password",
        "reset_password_new": "New Password",
        "reset_password_confirm": "Confirm Password",
        "reset_password_success_message": "Your new password has been set, and we've logged you in automatically.",
        "before_after_title": "Before / After Comparison",
        "before_after_need_scans": "You need at least two scans to compare",
        "before_after_need_scans_cta": "Do another skin scan to see how your skin has evolved over time",
        "before_after_before": "Before",
        "before_after_after": "After",
        "before_after_drag_hint": "Drag the handle left or right to compare",
        "before_after_metrics_compare": "Compare Metrics",
        "before_after_improved": "Improved %d%%",
        "before_after_increased": "Increased %d%%",
        "before_after_no_change": "No change",
        "before_after_before_percent": "Before: %d%%",
        "before_after_after_percent": "After: %d%%",
        "contact_us_title": "Contact Us",
        "contact_email_label": "Email",
        "contact_direct_label": "Direct Chat",
        "contact_direct_sub": "Available 9am–9pm",
        "contact_phone_label": "Phone Support",
        "contact_or_send_message": "Or send a message",
        "contact_subject_field": "Message Subject",
        "contact_subject_label": "Subject",
        "contact_details_label": "Message Details",
        "contact_message_placeholder": "Write your message here...",
        "contact_send_message": "Send Message",
        "contact_reply_time": "We'll reply within 24 business hours",
        "contact_success_message": "Your message has been sent successfully. Our support team will contact you within 24 hours.",
        "first_scan_title": "Let's Get to Know Your Skin",
        "first_scan_subtitle": "A quick AI scan, and we'll build you a fully custom routine and reports based on it",
        "first_scan_benefit1": "A full report on your skin condition",
        "first_scan_benefit2": "A daily care routine made for you",
        "first_scan_benefit3": "Suggested products that suit your skin exactly",
        "first_scan_start": "Start Your First Scan ✨",
        "first_scan_skip": "Skip for now",
        "sub_title": "Manage Subscription",
        "sub_active_renews": "Subscription active • Renews June 15, 2025",
        "sub_plans_title": "Subscription Plans",
        "sub_includes_title": "What's Included in Premium",
        "sub_feature1": "Unlimited AI skin scans",
        "sub_feature2": "Detailed weekly and monthly reports",
        "sub_feature3": "Product recommendations tailored to your skin",
        "sub_feature4": "Dermatologist expert consultations",
        "sub_feature5": "Smart routine that adapts to your skin",
        "sub_confirm_plan": "Confirm subscription to the %@ plan",
        "sub_plan_monthly": "Monthly",
        "sub_plan_yearly": "Yearly",
        "sub_plan_lifetime": "Lifetime",
        "sub_cancel": "Cancel Subscription",
        "sub_cancel_note": "You can cancel anytime up to 24 hours before renewal",
        "sub_cancel_confirm_message": "Your subscription will be cancelled at the end of the current period and won't renew.",
        "sub_plan_monthly_title": "Monthly",
        "sub_plan_yearly_title": "Yearly",
        "sub_plan_lifetime_title": "Lifetime",
        "sub_period_month": "/ month",
        "sub_period_year": "/ year",
        "sub_period_once": "one time",
        "sub_badge_save": "Save 32%",
        "sub_badge_best_value": "Best Value",
        "sub_cancel_confirm_button": "Confirm Cancellation",
        "sub_keep_subscription": "Keep Subscription",
        "skin_type_combination": "Combination",
        "skin_type_combination_desc": "Oily in the T-zone and dry on the cheeks",
        "skin_type_dry": "Dry",
        "skin_type_dry_desc": "Needs continuous, intensive hydration",
        "skin_type_oily": "Oily",
        "skin_type_oily_desc": "Excess oil production throughout the day",
        "skin_type_normal": "Normal",
        "skin_type_normal_desc": "Balanced and even skin",
        "skin_type_sensitive": "Sensitive",
        "skin_type_sensitive_desc": "Reacts quickly to products",
        "skin_profile_title": "Your Skin Profile",
        "skin_profile_concerns": "Detected Concerns",
        "skin_profile_update_note": "To update this, you need to do a new scan — not a manual edit, so the result stays accurate and reliable 💡",
        "skin_profile_no_scan": "You haven't done a skin scan yet",
        "skin_profile_no_scan_cta": "Go to the 'Skin Scan' tab and do your first scan so your real skin type shows up here",
        "done_button": "Done",
        "biometric_no_saved_creds": "No saved login data, please log in normally first",
        "biometric_reason": "Use your biometrics to log in quickly",
        "apple_auth_no_data": "Couldn't get login data from Apple",
        "apple_auth_failed": "Apple login failed: %@",
        "google_auth_start_failed": "Couldn't start login",
        "google_auth_failed": "Google login failed: %@",
        "google_auth_no_data": "Couldn't get login data from Google",
        "keyboard_done": "Done",
        "home_routine_default_summary": "Keep up with your daily routine 🌟",
        "home_view_all": "View All",
        "login_face_id": "Log in with Face ID",
        "login_touch_id": "Log in with Touch ID",
        "api_invalid_url": "Invalid URL",
        "api_network_error": "Connection error: %@",
        "api_network_error2": "Network connection error: %@",
        "api_invalid_response": "Invalid response from server",
        "api_read_response_failed": "Couldn't read server response",
        "api_read_response_failed2": "Couldn't read the response",
        "api_no_logged_user": "No logged in user",
        "api_must_login_first": "Please log in first",
        "api_need_scan_first": "You need to do a skin scan first so we can build a suitable routine for you",
        "api_wrong_current_password": "Current password is incorrect",
        "api_order_partial_save": "Order created but couldn't save all its details",
        "api_read_result_failed": "Couldn't read the analysis result",
        "api_upload_image_failed": "Couldn't upload the image: %@",
        "api_upload_image_failed2": "Couldn't upload the image",
        "api_save_changes_failed": "Couldn't save changes",
        "api_load_account_failed": "Couldn't load account data",
        "api_update_password_retry": "Couldn't update password, please try again",
        "api_update_password_failed": "Couldn't update password",
        "api_build_routine_retry": "Couldn't fully build the routine, please try again",
        "api_verify_account_failed": "Couldn't verify your account, please log in again",
        "api_server_connect_failed": "Couldn't connect to the server",
        "api_create_order_failed": "Couldn't create the order",
        "api_send_reset_link_retry": "Couldn't send the recovery link, please try again",
        "api_send_message_failed": "Couldn't send the message",
        "api_empty_response": "Empty response from server",
        "api_wrong_login_data": "Invalid login credentials",
        "api_wrong_otp": "Invalid verification code",
        "api_wrong_or_expired_code": "Code is invalid or expired",
        "api_apple_login_failed_generic": "Apple login failed",
        "api_google_login_failed_generic": "Google login failed",
        "notif_scan_ready_title": "Your scan is ready ✨",
        "notif_scan_ready_body": "Your skin health score: %d/100 — tap to see full details",
        "notif_order_update_title": "Order Update 🛍️",
        "order_status_pending": "Processing ⏳",
        "order_status_shipped": "Your order has shipped 📦",
        "order_status_delivered": "Your order has been delivered ✅",
        "order_status_cancelled": "Your order was cancelled ❌",
        "order_status_default": "Update on your order",
        "routine_tpl_cleanse_title": "Cleanse Skin",
        "routine_tpl_cleanse_note_morning": "Use a gentle cleanser suited to your skin type",
        "routine_tpl_cleanse_note_evening": "Remove any makeup or impurities to start your evening routine",
        "routine_tpl_treatment_title": "Targeted Treatment",
        "routine_tpl_treatment_note": "A serum that targets your detected skin concerns",
        "routine_tpl_moisturize_title": "Moisturize",
        "routine_tpl_moisturize_note": "A moisturizer suited to your skin type",
        "routine_tpl_moisturize_night_title": "Night Moisturizer",
        "routine_tpl_moisturize_night_note": "A night moisturizer that helps your skin while you sleep",
        "routine_tpl_sunscreen_title": "Sun Protection",
        "routine_tpl_sunscreen_note": "SPF 30+ sunscreen — a step you can't skip in the morning",
        "faq_q1": "How do I start a skin scan?",
        "faq_a1": "Tap the 'Skin Scan' button in the bottom bar, then point the camera at your face in good lighting and follow the instructions.",
        "faq_q2": "How often should I scan my skin?",
        "faq_a2": "We recommend a weekly scan for accurate tracking of improvements and changes in your skin.",
        "faq_q3": "Can I change my daily routine?",
        "faq_a3": "Yes, you can edit the routine from the Routine screen by tapping the edit button on each step.",
        "faq_q4": "How do I cancel my Premium subscription?",
        "faq_a4": "Go to Profile > Manage Subscription, then follow the cancel subscription option.",
        "help_title": "Help & Support",
        "help_faq_section": "Frequently Asked Questions",
        "help_contact_support": "Send a Support Message",
        "routine_morning_name": "Morning Routine",
        "routine_evening_name": "Evening Routine",
    ]
}
