import Foundation

/// قاموس الترجمات — كل شاشة نترجمها بنضيف مفاتيحها هون تحت تعليق باسم الشاشة.
/// أضيفي مفتاح جديد بالعربي والإنجليزي مع بعض دايماً عشان ما تنكسر الترجمة.
enum AppStrings {

    static let ar: [String: String] = [
        // MARK: - Splash
        "splash_tagline": "جمالكِ الذكي يبدأ هنا ✨",
        "splash_loading": "جاري التحميل...",

        // MARK: - Onboarding
        "onboarding_skip": "تخطي",
        "onboarding_next": "التالي",
        "onboarding_start": "ابدأ الآن",
        "onboarding_1_title": "فحص ذكي لبشرتك",
        "onboarding_1_desc": "مسح ضوئي دقيق باستخدام الذكاء الاصطناعي لتحليل بشرتك وفهم احتياجاتها في ثوانٍ.",
        "onboarding_2_title": "نقاط تقييم البشرة",
        "onboarding_2_desc": "احصلي على تقييم تفصيلي لصحة بشرتك مع تحليل دقيق للمسامات، الهالات، ونضارة الوجه.",
        "onboarding_3_title": "روتين مخصص لكِ",
        "onboarding_3_desc": "جدول عناية يومي مصمم خصيصاً ليناسب نوع بشرتك، مع تتبع مستمر للنتائج وتطور صحة البشرة.",
        "onboarding_1_pill1": "🤖 ذكاء اصطناعي", "onboarding_1_pill2": "📸 تحليل فوري", "onboarding_1_pill3": "✨ دقة عالية",
        "onboarding_2_pill1": "📊 تقييم شامل", "onboarding_2_pill2": "🔍 تحليل دقيق", "onboarding_2_pill3": "💡 نصائح ذكية",
        "onboarding_3_pill1": "📅 روتين يومي", "onboarding_3_pill2": "📈 تتبع التقدم", "onboarding_3_pill3": "🌟 نتائج ملحوظة",

        // MARK: - Login
        "login_welcome": "مرحباً بعودتك 💜",
        "login_email_label": "البريد الإلكتروني",
        "login_password_label": "كلمة المرور",
        "login_remember_me": "تذكرني",
        "login_forgot_password": "نسيت كلمة المرور؟",
        "login_or": "أو",
        "login_no_account": "ليس لديك حساب؟",
        "login_create_account": "إنشاء حساب",
        "login_button": "تسجيل الدخول",
        "login_error_email": "يرجى إدخال بريد إلكتروني صحيح",
        "login_error_password": "يرجى إدخال كلمة المرور",

        // MARK: - Signup
        "signup_title": "حساب جديد",
        "signup_subtitle": "ابدأي رحلتك مع GlowFit ✨",
        "signup_full_name": "الاسم الكامل",
        "signup_email": "البريد الإلكتروني",
        "signup_phone": "رقم الجوال",
        "signup_password": "كلمة المرور",
        "signup_gender": "الجنس",
        "signup_female": "أنثى",
        "signup_male": "ذكر",
        "signup_agree_to": "أوافق على",
        "signup_terms_privacy": "الشروط وسياسة الخصوصية",
        "signup_or": "أو",
        "signup_have_account": "لديك حساب بالفعل؟",
        "signup_login": "تسجيل الدخول",
        "signup_button": "إنشاء الحساب",
        "signup_placeholder_name": "أدخلي اسمك الكامل",
        "signup_placeholder_password": "8 أحرف على الأقل",
        "signup_error_terms": "يرجى الموافقة على الشروط وسياسة الخصوصية أولاً",
        "signup_error_url": "رابط الباك آند غير صحيح",
        "signup_error_data": "خطأ في معالجة البيانات",
        "signup_error_network": "خطأ في الاتصال بالشبكة: %@",
        "signup_error_response": "استجابة غير صالحة من خادم الباك آند",
        "signup_error_exists": "هذا البريد الإلكتروني مسجل عندنا بالفعل. سجّلي دخول بدلاً من ذلك.",
        "signup_error_generic": "حدث خطأ أثناء إنشاء الحساب (رمز الخطأ: %d)",
        "signup_error_already_registered": "هذا البريد الإلكتروني مسجل بالفعل",
        "signup_error_password_length": "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
        "signup_error_invalid_email": "يرجى إدخال بريد إلكتروني صحيح",
        "signup_error_rate_limit": "تم تجاوز حد الطلبات المسموح به، يرجى المحاولة لاحقاً",

        // MARK: - Home
        "home_greeting": "مرحباً 👋",
        "home_skin_score_title": "تقييم بشرتك (آخر فحص)",
        "home_no_scan_yet": "لسا ما سويتِ فحص بشرة ✨",
        "home_no_scan_cta": "دوسي هون لتسويي فحصك الأول وتفعيل التقارير والروتين المخصص",
        "home_no_routine_cta": "لسا ما بنيتي روتينك — دوسي هون لتبنيه ✨",
        "home_quick_scan": "فحص البشرة",
        "home_action_report_title": "تقرير مفصّل",
        "home_action_report_subtitle": "نتائج آخر فحص",
        "home_action_routine_title": "الروتين اليومي",
        "home_action_routine_subtitle": "3 خطوات متبقية",
        "home_routine_morning": "روتينك الصباحي ☀️",
        "home_routine_evening": "روتينك المسائي 🌙",
        "home_no_morning_routine": "ما في روتين صباحي مبني بعد",
        "home_no_evening_routine": "ما في روتين مسائي مبني بعد",
        "tab_home": "الرئيسية",
        "tab_reports": "التقارير",
        "tab_routine": "الروتين",
        "tab_profile": "حسابي",

        // MARK: - Skin Scan
        "scan_title": "فحص البشرة",
        "scan_view_last_result": "عرض آخر نتيجة فحص",
        "scan_lighting_tip": "تأكدي من الإضاءة الجيدة وعدم وجود مكياج للحصول على أدق النتائج ✨",
        "scan_analyzing": "جاري تحليل بشرتك...",
        "scan_analyzing_sub": "الذكاء الاصطناعي يقوم بفحص مسامك والتجاعيد",
        "scan_help_tips": "• استخدمي إضاءة طبيعية جيدة (قرب نافذة مثلاً)\n• شيلي المكياج قبل الفحص\n• خلي وجهك واضح بدون نظارات أو غطاء\n• انظري مباشرة للكاميرا وبمسافة معقولة",
        "scan_result_title": "نتيجة فحص بشرتك",
        "scan_out_of_100": "من 100",
        "scan_health_score": "درجة صحة البشرة",
        "scan_first_scan_note": "🎉 هذا فحصك الأول — رح نقارن نتائجك القادمة فيه",
        "scan_approx_age": "العمر التقريبي للبشرة: %d سنة",
        "scan_problems_solutions": "⚠️ المشاكل والحلول",
        "scan_source": "المصدر: ",
        "scan_detected_problems": "⚠️ مشاكل مكتشفة",
        "scan_recommendations": "توصيات العناية",
        "scan_suggested_products": "🛍 منتجات مقترحة لك",
        "scan_currency": "ر.س",
        "scan_done": "تم",
        "scan_help_title": "نصائح لأدق نتيجة 💡",
        "scan_help_ok": "تمام، فهمت 👍",
        "scan_price_format": "%d ر.س",
        "scan_scanning_guide": "جاري الفحص... يرجى الثبات 📸",
        "scan_frame_face": "ضعي وجهك داخل الإطار 👤",
        "scan_improved": "تحسّن +%d عن الفحص السابق",
        "scan_declined": "تراجع %d عن الفحص السابق",
        "scan_no_change": "بدون تغيير عن الفحص السابق",

        // MARK: - Reports
        "report_no_reports_yet": "لسا ما عندك تقارير",
        "report_no_reports_cta": "سوّي فحص بشرة أول عشان يبدأ يتكوّن تقريرك هون",
        "report_title": "تقرير البشرة",
        "report_before_after": "مقارنة قبل / بعد",
        "report_comparison_title": "مقارنة نتائج آخر %d فحوصات",
        "report_based_on_last_scan": "بناءً على آخر فحص",
        "report_detailed_analysis": "تحليل مفصّل",
        "report_time_evolution": "التطور الزمني",
        "report_ai_advice_title": "نصيحة خبير الذكاء الاصطناعي",
        "report_history": "سجل التقارير",
        "report_filter_title": "فلترة التقرير",
        "report_visible_metrics": "المقاييس المعروضة",
        "report_date_range": "نطاق الفترة الزمنية: آخر %d أسبوع",
        "report_apply_filter": "تطبيق الفلتر",
        "report_detail_title": "تفاصيل التقرير",
        "report_points_suffix": "نقطة",
        "report_findings": "⚠️ ملاحظات مكتشفة",
        "report_problems_solutions": "🩺 المشاكل والحلول",
        "report_care_recommendations": "💡 توصيات العناية",
        "metric_moisture": "مستوى الترطيب",
        "metric_acne": "حب الشباب",
        "metric_dark_circles": "الهالات السوداء",
        "metric_fine_lines": "الخطوط الدقيقة",
        "metric_key_moisture": "الترطيب",
        "metric_key_acne": "حب الشباب",
        "metric_key_darkCircles": "الهالات",
        "metric_key_fineLines": "الخطوط",
        "report_share_intro": "حللت بشرتي بالذكاء الاصطناعي مع GlowFit AI ✨",
        "report_share_score": "درجة صحة بشرتي: %d/100",
        "report_share_cta": "جرّبي أنتِ كمان وشوفي تحليل بشرتك:",
        "report_status_improved": "تحسّن",
        "report_status_declined": "تراجع",
        "report_status_unchanged": "بدون تغيير",

        // MARK: - Routine
        "routine_morning_tab": "الصباح ☀️",
        "routine_evening_tab": "المساء 🌙",
        "routine_no_routine_yet": "لسا ما عندك روتين",
        "routine_no_routine_cta": "بنبني لك روتين صباحي ومسائي مخصص بناءً على آخر فحص بشرة سويتيه",
        "routine_build_now": "بناء روتيني الآن ✨",
        "routine_care_title": "روتين العناية",
        "routine_care_subtitle": "خطواتك اليومية للبشرة",
        "routine_steps_completed_today": "خطوات مكتملة اليوم",
        "routine_streak_days": "%d يوم",
        "routine_steps_label": "الخطوات",
        "routine_add_step": "إضافة خطوة",
        "routine_delete": "حذف",
        "routine_delete_confirm_title": "حذف الخطوة؟",
        "routine_delete_confirm_message": "راح تنحذف هاي الخطوة نهائياً من روتينك.",
        "routine_choose_icon": "اختاري أيقونة",
        "routine_enable_reminder": "تفعيل تذكير يومي",
        "routine_add_step_title": "إضافة خطوة جديدة",
        "routine_add_step_button": "إضافة الخطوة",
        "routine_reminder_time_morning": "الوقت (فترة صباحية ☀️ من 4:00 لـ 11:59 ص)",
        "routine_reminder_time_evening": "الوقت (فترة مسائية 🌙 من 4:00 لـ 11:59 م)",
        "routine_reminder_title": "تذكير: %@",
        "routine_step_default_name": "خطوة",
        "routine_enable_step_reminder": "تفعيل تذكير يومي لهاي الخطوة",
        "routine_save": "حفظ",
        "routine_tip_of_day": "نصيحة اليوم",
        "routine_tip_morning": "نصيحة: ضعي واقي الشمس كآخر خطوة قبل الخروج بـ 15 دقيقة لأفضل حماية ☀️",
        "routine_tip_evening": "نصيحة: تجنبي لمس وجهك بعد السيروم واتركيه يمتص بالكامل قبل النوم 🌙",
        "field_step_name": "اسم الخطوة",
        "field_note_optional": "ملاحظة (اختياري)",
        "routine_all_done_today": "خلصتي كل خطوات اليوم! 🎉",
        "routine_keep_going": "تقدم رائع! استمري 💪",

        // MARK: - Store
        "store_no_products": "ما في منتجات متاحة حالياً",
        "store_title": "المتجر 🛍️",
        "store_subtitle": "منتجات مختارة لبشرتك",
        "store_search_placeholder": "ابحثي عن منتج...",
        "store_ai_picked": "اختار AI منتجاتك!",
        "store_ai_picked_desc": "نسبة التطابق محسوبة بناءً على نوع بشرتك ونتائج فحصك الأخير",
        "store_match_percent": "%d%% تطابق",
        "store_match_with_skin": "%d%% تطابق مع بشرتك",
        "store_add_to_cart": "أضف إلى السلة",
        "store_added_confirm": "أُضيفت ✓",
        "store_add_short": "أضف للسلة",
        "store_default_product_name": "منتج",

        // MARK: - Cart & Orders
        "cart_title": "سلة المشتريات 🛒",
        "cart_empty": "السلة فارغة",
        "cart_empty_cta": "تصفحي المتجر واختاري المنتجات المناسبة لبشرتك",
        "cart_back_to_store": "العودة للمتجر",
        "cart_order_summary": "ملخص الطلب",
        "cart_total": "الإجمالي",
        "cart_price_format": "%d ر.س",
        "cart_checkout": "إتمام الطلب",
        "cart_order_success": "تم استلام طلبك بنجاح! 🎉",
        "cart_track_order": "تتبع الطلب",
        "orders_title": "طلباتي 📦",
        "orders_empty": "لسا ما عندك طلبات",
        "orders_number_format": "طلب #%@",
        "cart_subtotal": "المجموع الفرعي",
        "cart_tax": "الضريبة (15%)",
        "cart_delivery": "التوصيل",
        "cart_free": "مجاني",
        "cart_thank_you": "شكراً لتسوقك معنا. سنقوم بتجهيز طلبك وشحنه في أقرب وقت ممكن.",
    ]

    static let en: [String: String] = [
        // MARK: - Splash
        "splash_tagline": "Your smart glow starts here ✨",
        "splash_loading": "Loading...",

        // MARK: - Onboarding
        "onboarding_skip": "Skip",
        "onboarding_next": "Next",
        "onboarding_start": "Get Started",
        "onboarding_1_title": "Smart Skin Scan",
        "onboarding_1_desc": "A precise AI-powered scan that analyzes your skin and understands its needs in seconds.",
        "onboarding_2_title": "Skin Health Score",
        "onboarding_2_desc": "Get a detailed assessment of your skin health with accurate analysis of pores, dark circles, and radiance.",
        "onboarding_3_title": "A Routine Made For You",
        "onboarding_3_desc": "A daily care schedule designed specifically for your skin type, with continuous tracking of results and skin health progress.",
        "onboarding_1_pill1": "🤖 AI Powered", "onboarding_1_pill2": "📸 Instant Analysis", "onboarding_1_pill3": "✨ High Accuracy",
        "onboarding_2_pill1": "📊 Full Assessment", "onboarding_2_pill2": "🔍 Precise Analysis", "onboarding_2_pill3": "💡 Smart Tips",
        "onboarding_3_pill1": "📅 Daily Routine", "onboarding_3_pill2": "📈 Progress Tracking", "onboarding_3_pill3": "🌟 Visible Results",

        // MARK: - Login
        "login_welcome": "Welcome back 💜",
        "login_email_label": "Email",
        "login_password_label": "Password",
        "login_remember_me": "Remember me",
        "login_forgot_password": "Forgot password?",
        "login_or": "or",
        "login_no_account": "Don't have an account?",
        "login_create_account": "Create account",
        "login_button": "Log In",
        "login_error_email": "Please enter a valid email",
        "login_error_password": "Please enter your password",

        // MARK: - Signup
        "signup_title": "New Account",
        "signup_subtitle": "Start your journey with GlowFit ✨",
        "signup_full_name": "Full Name",
        "signup_email": "Email",
        "signup_phone": "Phone Number",
        "signup_password": "Password",
        "signup_gender": "Gender",
        "signup_female": "Female",
        "signup_male": "Male",
        "signup_agree_to": "I agree to the",
        "signup_terms_privacy": "Terms & Privacy Policy",
        "signup_or": "or",
        "signup_have_account": "Already have an account?",
        "signup_login": "Log In",
        "signup_button": "Create Account",
        "signup_placeholder_name": "Enter your full name",
        "signup_placeholder_password": "At least 8 characters",
        "signup_error_terms": "Please agree to the Terms & Privacy Policy first",
        "signup_error_url": "Invalid backend URL",
        "signup_error_data": "Error processing data",
        "signup_error_network": "Network connection error: %@",
        "signup_error_response": "Invalid response from backend server",
        "signup_error_exists": "This email is already registered. Please log in instead.",
        "signup_error_generic": "An error occurred while creating the account (error code: %d)",
        "signup_error_already_registered": "This email is already registered",
        "signup_error_password_length": "Password must be at least 8 characters",
        "signup_error_invalid_email": "Please enter a valid email",
        "signup_error_rate_limit": "Request limit exceeded, please try again later",

        // MARK: - Home
        "home_greeting": "Hello 👋",
        "home_skin_score_title": "Your Skin Score (Last Scan)",
        "home_no_scan_yet": "You haven't scanned your skin yet ✨",
        "home_no_scan_cta": "Tap here to do your first scan and unlock reports and a custom routine",
        "home_no_routine_cta": "You haven't built your routine yet — tap here to build it ✨",
        "home_quick_scan": "Skin Scan",
        "home_action_report_title": "Detailed Report",
        "home_action_report_subtitle": "Latest scan results",
        "home_action_routine_title": "Daily Routine",
        "home_action_routine_subtitle": "3 steps remaining",
        "home_routine_morning": "Your Morning Routine ☀️",
        "home_routine_evening": "Your Evening Routine 🌙",
        "home_no_morning_routine": "No morning routine built yet",
        "home_no_evening_routine": "No evening routine built yet",
        "tab_home": "Home",
        "tab_reports": "Reports",
        "tab_routine": "Routine",
        "tab_profile": "Profile",

        // MARK: - Skin Scan
        "scan_title": "Skin Scan",
        "scan_view_last_result": "View last scan result",
        "scan_lighting_tip": "Make sure you have good lighting and no makeup for the most accurate results ✨",
        "scan_analyzing": "Analyzing your skin...",
        "scan_analyzing_sub": "AI is examining your pores and wrinkles",
        "scan_help_tips": "• Use good natural lighting (near a window, for example)\n• Remove makeup before scanning\n• Keep your face clear without glasses or coverings\n• Look directly at the camera at a reasonable distance",
        "scan_result_title": "Your Skin Scan Result",
        "scan_out_of_100": "out of 100",
        "scan_health_score": "Skin Health Score",
        "scan_first_scan_note": "🎉 This is your first scan — we'll compare your future results to it",
        "scan_approx_age": "Approximate skin age: %d years",
        "scan_problems_solutions": "⚠️ Problems & Solutions",
        "scan_source": "Source: ",
        "scan_detected_problems": "⚠️ Detected Issues",
        "scan_recommendations": "Care Recommendations",
        "scan_suggested_products": "🛍 Suggested Products For You",
        "scan_currency": "SAR",
        "scan_done": "Done",
        "scan_help_title": "Tips For Best Results 💡",
        "scan_help_ok": "Got it 👍",
        "scan_price_format": "%d SAR",
        "scan_scanning_guide": "Scanning... please hold still 📸",
        "scan_frame_face": "Place your face inside the frame 👤",
        "scan_improved": "Improved +%d since last scan",
        "scan_declined": "Down %d since last scan",
        "scan_no_change": "No change since last scan",

        // MARK: - Reports
        "report_no_reports_yet": "You don't have any reports yet",
        "report_no_reports_cta": "Do a skin scan first so your report can start forming here",
        "report_title": "Skin Report",
        "report_before_after": "Before / After Comparison",
        "report_comparison_title": "Comparing results of last %d scans",
        "report_based_on_last_scan": "Based on your last scan",
        "report_detailed_analysis": "Detailed Analysis",
        "report_time_evolution": "Progress Over Time",
        "report_ai_advice_title": "AI Expert Advice",
        "report_history": "Report History",
        "report_filter_title": "Filter Report",
        "report_visible_metrics": "Visible Metrics",
        "report_date_range": "Time range: last %d weeks",
        "report_apply_filter": "Apply Filter",
        "report_detail_title": "Report Details",
        "report_points_suffix": "points",
        "report_findings": "⚠️ Detected Notes",
        "report_problems_solutions": "🩺 Problems & Solutions",
        "report_care_recommendations": "💡 Care Recommendations",
        "metric_moisture": "Moisture Level",
        "metric_acne": "Acne",
        "metric_dark_circles": "Dark Circles",
        "metric_fine_lines": "Fine Lines",
        "metric_key_moisture": "Moisture",
        "metric_key_acne": "Acne",
        "metric_key_darkCircles": "Dark Circles",
        "metric_key_fineLines": "Fine Lines",
        "report_share_intro": "I analyzed my skin with AI using GlowFit AI ✨",
        "report_share_score": "My skin health score: %d/100",
        "report_share_cta": "Try it yourself and see your skin analysis:",
        "report_status_improved": "Improved",
        "report_status_declined": "Declined",
        "report_status_unchanged": "Unchanged",

        // MARK: - Routine
        "routine_morning_tab": "Morning ☀️",
        "routine_evening_tab": "Evening 🌙",
        "routine_no_routine_yet": "You don't have a routine yet",
        "routine_no_routine_cta": "We'll build you a custom morning and evening routine based on your last skin scan",
        "routine_build_now": "Build My Routine Now ✨",
        "routine_care_title": "Care Routine",
        "routine_care_subtitle": "Your daily skin steps",
        "routine_steps_completed_today": "Steps completed today",
        "routine_streak_days": "%d days",
        "routine_steps_label": "Steps",
        "routine_add_step": "Add Step",
        "routine_delete": "Delete",
        "routine_delete_confirm_title": "Delete this step?",
        "routine_delete_confirm_message": "This step will be permanently removed from your routine.",
        "routine_choose_icon": "Choose an icon",
        "routine_enable_reminder": "Enable daily reminder",
        "routine_add_step_title": "Add New Step",
        "routine_add_step_button": "Add Step",
        "routine_reminder_time_morning": "Time (morning window ☀️ 4:00 AM to 11:59 AM)",
        "routine_reminder_time_evening": "Time (evening window 🌙 4:00 PM to 11:59 PM)",
        "routine_reminder_title": "Reminder: %@",
        "routine_step_default_name": "Step",
        "routine_enable_step_reminder": "Enable daily reminder for this step",
        "routine_save": "Save",
        "routine_tip_of_day": "Tip of the Day",
        "routine_tip_morning": "Tip: Apply sunscreen as your last step 15 minutes before going out for best protection ☀️",
        "routine_tip_evening": "Tip: Avoid touching your face after applying serum and let it fully absorb before sleeping 🌙",
        "field_step_name": "Step Name",
        "field_note_optional": "Note (optional)",
        "routine_all_done_today": "You've completed all of today's steps! 🎉",
        "routine_keep_going": "Great progress! Keep going 💪",

        // MARK: - Store
        "store_no_products": "No products available right now",
        "store_title": "Store 🛍️",
        "store_subtitle": "Products picked for your skin",
        "store_search_placeholder": "Search for a product...",
        "store_ai_picked": "AI Picked Your Products!",
        "store_ai_picked_desc": "Match percentage calculated based on your skin type and latest scan results",
        "store_match_percent": "%d%% match",
        "store_match_with_skin": "%d%% match with your skin",
        "store_add_to_cart": "Add to Cart",
        "store_added_confirm": "Added ✓",
        "store_add_short": "Add to Cart",
        "store_default_product_name": "Product",

        // MARK: - Cart & Orders
        "cart_title": "Shopping Cart 🛒",
        "cart_empty": "Your cart is empty",
        "cart_empty_cta": "Browse the store and pick products suited for your skin",
        "cart_back_to_store": "Back to Store",
        "cart_order_summary": "Order Summary",
        "cart_total": "Total",
        "cart_price_format": "%d SAR",
        "cart_checkout": "Checkout",
        "cart_order_success": "Your order was placed successfully! 🎉",
        "cart_track_order": "Track Order",
        "orders_title": "My Orders 📦",
        "orders_empty": "You don't have any orders yet",
        "orders_number_format": "Order #%@",
        "cart_subtotal": "Subtotal",
        "cart_tax": "Tax (15%)",
        "cart_delivery": "Delivery",
        "cart_free": "Free",
        "cart_thank_you": "Thank you for shopping with us. We'll prepare and ship your order as soon as possible.",
    ]
}
